Repository spatialos/database-sync-worker, pull requests merged in 2019-09, with the labels that each got.

#5 Os 297 system entities
  CSharpCodeGenerator/CSharpCodeGenerator.Test/CSharpCodeGenerator.Test.csproj
  CSharpCodeGenerator/CSharpCodeGenerator/CSharpCodeGenerator.csproj
  GeneratedCode/GeneratedCode.csproj
  README.md
  Workers/DatabaseSyncWorker/DatabaseChanges.cs
  Workers/DatabaseSyncWorker/DatabaseSyncLogic.cs
  Workers/DatabaseSyncWorker/DatabaseSyncWorker.csproj
  Workers/DatabaseSyncWorker/IOptions.cs
  Workers/DatabaseSyncWorker/LocatorOptions.cs
  Workers/DatabaseSyncWorker/Program.cs
  ci/docker/linux.Dockerfile
  ci/pinned-tools.sh
  scripts/BuildNugetPackages/Program.cs
Labels: jira/no-ticket, size/XL

#6 Os 386 cancellation tokens
  CSharpCodeGenerator/CSharpCodeGenerator/CSharpCodeGenerator.csproj
  Workers/DatabaseSyncWorker/DatabaseChanges.cs
  Workers/DatabaseSyncWorker/DatabaseSyncLogic.cs
  scripts/BuildNugetPackages/Program.cs
Labels: jira/no-ticket, size/M

#7 More debugging
  scripts/GetDependentBranchNames/Program.cs
Labels: jira/no-ticket, size/XS

#8 added CI step for test annotations
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/S

#9 Feature/upgrade to 14.1
  Bootstrap/Bootstrap.csproj
  CSharpCodeGenerator/CSharpCodeGenerator.Test/CSharpCodeGenerator.Test.csproj
  CSharpCodeGenerator/CSharpCodeGenerator/CSharpCodeGenerator.csproj
  GeneratedCode/GeneratedCode.csproj
  README.md
  Workers/DatabaseSyncWorker/AsyncConnectionExtensions.cs
  Workers/DatabaseSyncWorker/DatabaseChanges.cs
  Workers/DatabaseSyncWorker/DatabaseSyncLogic.cs
  Workers/DatabaseSyncWorker/DatabaseSyncWorker.csproj
  ci/docker/linux.Dockerfile
  scripts/BuildNugetPackages/BuildNugetPackages.csproj
  scripts/BuildNugetPackages/Program.cs
  scripts/GetDependentBranchNames/GetDependentBranchNames.csproj
Labels: jira/no-ticket, size/M
